name: Bilibili Lottery

on:
  schedule:
    - cron: '0 4 * * *'  # UTC 4:00 = 北京时间 12:00
  workflow_dispatch:        # 允许手动触发

jobs:
  lottery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run lottery script
      env:
        BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      run: python main.py
